# Strings used in logs
cli:
    # String to represent that something succeded
    status_ok: "OK"

    # String to represent that something failed
    status_bad: "BAD"

log:
    enabled: false
    filePath: "./logs/"

# The user id of the bot owner
ownerId: "529424782438170679"

# The user ids of the bot developers
developersId:
    - "529424782438170679"

# Guild that will be used for testing
# Commands marked as DEV will be set here
devGuildId: "998487239803813898"

# Main guild
mainGuildId: "998487239803813898"

# Custom emojis used in messages/embeds
icons:
    loading: "<a:loading:1013023173635211365>"

    # Used to represent the database status for connecting/disconnecting
    sync: "<:sync:1042093144369537074>"

    # Used to represent true
    true: "<:true:1010479956909891614>"

    # Used to represent false
    false: "<:false:1010479954372349993>"

    # Used to represent unknown values
    unknown: "<:unknown:1143153276934684712>"

    bot:
        #  Used as prefix for the username in /about user (src/commands/misc/about/about.user.ts) if the user's id is included in `developersId`
        developer: "<a:developer:1010538744803233822>"

    server:
        # Used as prefix for the username in /about user (src/commands/misc/about/about.user.ts) if the user is the owner of the guild
        owner: "<:server_owner:1010487201810874470>"

        # Used as prefix for the server name in /about server (src/commands/misc/about/about.server.ts) if the server is verified
        verified: "<:server_verified:1010152556405739611>"

        # Used as prefix for the server name in /about server (src/commands/misc/about/about.server.ts) if the server is partnered
        partnered: "<:server_partnered:1010152578010579006>"

    alka:
        # Used as prefix for the username in in /about user (src/commands/misc/about/about.user.ts) if the user is a custom bot made for Alka Hangout
        bot: "<:alka_bot:1010540470109225061>"

alka:
    # The user ids of bots custom made for Alka Hangout (icons -> alka -> bot will be displayed as a prefix)
    bots:
        - "1016267923985281024"
        - "798420219005239326"
        - "888023934207934505"

# Colors used in embeds
colors:
    # Bot theme color
    theme: "#615fd9"

    # Color to represent that something succeded
    succesful: "#6dd95f"

    # Color to represent that something failed
    failed: "#d95f5f"

# OAuth2 settings
oauth2:
    # Client ID
    clientId: "1120640044689006633"

    # OAuth2 redirect url
    redirect: "/auth/redirect"
