# Strings used in logs
cli:
    # String to represent that something succeded
    status_ok: "OK"

    # String to represent that something failed
    status_bad: "BAD"

log:
    enabled: false
    filePath: "./logs/"

# The user id of the bot owner
ownerId: "529424782438170679"

# The user ids of the bot developers
developersId:
    - "529424782438170679"

# Guild that will be used for testing
# Commands marked as DEV will be set here
devGuildId: "998487239803813898"

# Main guild
mainGuildId: "998487239803813898"

# Custom emojis used in messages/embeds
icons:
    loading: "<a:loading:1013023173635211365>"

    # Used to represent the database status for connecting/disconnecting
    sync: "<:sync:1042093144369537074>"

    # Used to represent true
    true: "<:indicator_true:1150381765828026428>"

    # Used to represent false
    false: "<:indicator_false:1150381760341880873>"

    # Used to represent unknown values
    unknown: "<:indicator_undefined:1150381784215863377>"

    shield:
        checkmark: "<:shield_good:1149673417839214662>"
        cancel: "<:shield_bad:1149673413946908682>"
        exclamation_yellow: "<:shield_exclamation_yellow:1150042656706146375>"
        exclamation_red: "<:shield_exclamation_red:1150041407994740837>"

# Colors used in embeds
colors:
    # Bot theme color
    theme: "#615fd9"

    # Color to represent that something succeded
    succesful: "#6dd95f"

    # Color to represent that something failed
    failed: "#d95f5f"

    # Colors to represent that something bad happened (not failed)
    bad: "#d95f5f"

    # Colors to represent warnings
    warning: "#d9cd5f"

# OAuth2 settings
oauth2:
    # Client ID
    clientId: "1120640044689006633"

    # OAuth2 redirect url
    redirect: "/auth/redirect"
