name: build and run

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install dependencies
              run: npm ci

            - name: Compile to JavaScript using esbuild
              run: npm run build

            - name: Run
              run: npm run test
              env:
                  TOKEN: ${{ secrets.TOKEN }}
                  MONGODB: ${{ secrets.MONGODB }}
                  # ANTICRASH: ${{ secrets.ANTICRASH }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
                  EXPRESS_PORT: 8080
                  SOCKETIO_PORT: 3000
